[project]
name = "programming-paradigms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nbconvert>=7.16.4",
    "notebook>=7.2.2",
]
