project:
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/JoseBlanca/programming_paradigms
  repo-actions: [source, issue]
  title: "Procedural, Object Oriented and functional programming"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
