project:
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/JoseBlanca/programming_paradigms
  repo-actions: [source, issue]
  title: "Procedural, Object Oriented and functional programming"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Procedural"
        href: "procedural.qmd"
      - text: "Objects and classes"
        href: "objects_and_classes.qmd"
      - text: "Functional programming"
        href: "functional_programming.qmd"
      - text: "Exercises"
        href: "exercises.qmd"